version: '3.8'

services:
  task6:
    build: ./app
    container_name: ctf_guard_server
    ports:
      - "8080:8080"  # Змінено тут
    environment:
      - PORT=8080    # Змінено тут
    restart: unless-stopped