version: '3.8'

services:
  task6:
    build: ./app
    image: castlesec-task6:latest
    ports:
      - "8080:8080"  # Змінено тут
    environment:
      - PORT=8080    # Змінено тут
    restart: unless-stopped