services:
  t9-library:
    build: .
    container_name: task9
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BASE_DIR=/data/keep/west_tower/library/scriptorium
      - FLAG_FILE=/data/keep/royal_quarter/inner_palace/antechamber/seal_vault/royal_sigil.txt
      - KEEP_DIR=/data/keep
    volumes:
      - ./data:/data:ro
    restart: unless-stopped