server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Дозволяємо доступ до папки .git (вразливість)
    location ^~ /.git {
        allow all;
        autoindex on; # Щоб можна було бачити список файлів репозиторію
    }

    location / {
        try_files $uri $uri/ =404;
    }
}