version: '3'
services:
  task4:
    build: ./app
    image: castlesec-task4:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - DEBUG_LEVEL=verbose
      - SECRET_KEY=FLAG{ALWAYS_CHECK_HTML_COMMENTS}
    restart: unless-stopped
